### ISSUE TITLE
roman.py mentions both Zope Public License and Python 2.1.1 license

### ISSUE THREAD

**Issue by mitya57** [zopefoundation/roman#17]
In #16, this project was relicensed as Zope Public License 2.1. However, the source file still mentions both licenses. Lines 6-11 mention the Zope Public License:

https://github.com/zopefoundation/roman/blob/fa38244b6a30f21bfb8b9002cc81e7f172c59512/src/roman.py#L6-L11

And lines 25-27 mention the Python 2.1.1 license:

https://github.com/zopefoundation/roman/blob/fa38244b6a30f21bfb8b9002cc81e7f172c59512/src/roman.py#L25-L27

I assume this is an oversight? If yes, can the mentions of Python license be removed?

**Comment by dataflake** [comment]
Solved in 265bac2e1c637b622bc2305beab5ef5db8346bcb

You are right, that was overlooked. Thanks for letting us know. I have released version 4.2 with the change.
