### ISSUE TITLE
Incorrect version string.

### ISSUE THREAD

**Issue by jenstroeger** [zopefoundation/roman#24]
### What I did:

```python
>>> import roman
>>> roman.__version__
'1.4'
```

### What I expect to happen:

Should show the current version, but https://github.com/zopefoundation/roman/blob/8afcfcf66dd28517179ae657c2d0c97b163a7ee3/src/roman.py#L17-L17

### What actually happened:

See above.

**Comment by dataflake** [comment]
These markers were unsupported and unmaintained for over 10 years. I have removed the version and date markers. The package version and the release dates are clearly visible in the change log and in the package version itself, so they are not needed.

**Comment by jenstroeger** [comment]
Ouch, I disagree with removing those: some dunder constants like `__version__` recommended and expected by tooling. See for example the Python documentation [here](https://peps.python.org/pep-0008/#module-level-dunder-names) or [here](https://packaging.python.org/en/latest/guides/single-sourcing-package-version/).

**Comment by perrinjerome** [comment]
Isn't it "better" to use `importlib.metadata.version` these days ( https://docs.python.org/3/library/importlib.metadata.html#distribution-versions ) ?

**Comment by dataflake** [comment]
`roman` is one package out of over 300 in the zopefoundation organization. We don't use these dunders. They add maintenance burden that I personally am unwilling to carry.

**Comment by icemac** [comment]
Just released https://pypi.org/project/roman/5.0/ containing a fix.
