### ISSUE TITLE
Add roman as a package on conda-forge

### ISSUE THREAD

**Issue by namurphy** [zopefoundation/roman#3]
While trying to put our package on [conda-forge](https://conda-forge.org/), we ran into a problem since we have roman as a dependency and roman is not on conda-forge.  It would be helpful to the conda-forge community if roman were made available on conda-forge as well, especially since I don't know of any similar packages on conda-forge already.  

In the meantime, our workaround will likely be putting `roman.py` and the license into an `extern` directory inside of our package (in case anyone else runs into this issue).

Thank you for making this package available.  It has been really helpful!

**Comment by jamadden** [comment]
AIUI, that’s completely independent of this repository. I don’t think zooefoundation has any particular presence or policy about conda, it’s just another downstream packager.

**Comment by dataflake** [comment]
Closing this as invalid because we have no control over if/how this package is available on conda-forge.
