### ISSUE TITLE
License

### ISSUE THREAD

**Issue by thewchan** [zopefoundation/roman#8]
Hello, I'm in the process of adding this package to the conda-forge repository, and they require each package to adopt some kind of license. I notice that ``roman`` does not specify which license apply here (at least on on the github page). Might I suggest using the no-frills MIT license? If that's okay I can make a PR to add a license file in. Thanks!

**Comment by thewchan** [comment]
My mistake; I now see in your code base that you are using https://opensource.org/licenses/ZPL-2.0 for your license. However, the code base still lacks a ``LICENSE`` file, and I think can add one real quick with the ZPL-2.0 text via PR. Would that be acceptable?

**Comment by dataflake** [comment]
Actually, the main module is licensed under the Python Software Foundation license, I changed the file.

**Comment by thewchan** [comment]
@dataflake Thanks, the package is now published over at Conda-forge; thanks so much for your help on this! I'll keep an eye out for any new releases over here and update the package over at Conda-forge.
