### ISSUE TITLE
Packaging license file

### ISSUE THREAD

**Issue by jakirkham** [zopefoundation/roman#9]
## BUG/PROBLEM REPORT (OR OTHER COMMON ISSUE)

Currently the license file is not being packaged in the wheel or the sdist.

### What I did:

Looked at the archives and did not find it. Not seeing the code here needed to include the license file either.

### What I expect to happen:

The license file to be packaged for end users.

This can be addressed by adding the `license_file` to `setup.py` and specifying the license file name. Relevant [setuptools docs]( https://setuptools.readthedocs.io/en/latest/userguide/declarative_config.html?highlight=license_files#metadata ).

### What actually happened:

The license file is missing.

### What version of Python and Zope/Addons I am using:

3.3

**Comment by dataflake** [comment]
The license file is added in this repository now. The license was already clearly specified in `setup.py` using the `license` keyword.
